- name: "Install nginx"
  become: "yes"
  dnf:
    name: "nginx" 
    state: "present"

- name: "Enable and Start nginx"
  become: "yes"
  systemd:
    name: "nginx"
    enabled: "yes"
    state: "started"


- name: "setup_ssl_server"
  include: "setup_ssl.yml"
  tags:
    - setup_ssl
